In [1]:
import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv('/Users/tyco/Desktop/MADS/sanovo_19052025/data/processed/cleaned_data.csv')
df.head(5)

,MerId,MerType,MerDate,MerNumber,MerSubNumber,MerData1,MerData2,MerData3,MerData4,MerData5,MerMinId,MerText,MerDeviceType,MerDeviceNumber,MerPriority,MerDateDay
0,11897185,7,2025-01-30 10:22:00,10,22,181.0,180.0,90.0,NaN,NaN,4620,NaN,0,0,0,2025-01-30
1,11897186,21,2025-01-30 10:21:42,460,12,1.0,22.0,41.0,NaN,NaN,4620,NaN,0,0,0,2025-01-30
2,11897187,23,2025-01-30 10:21:56,460,12,0.0,0.0,0.0,NaN,NaN,4620,NaN,0,0,0,2025-01-30
3,11897188,21,2025-01-30 10:21:56,460,12,1.0,22.0,41.0,NaN,NaN,4620,NaN,0,0,0,2025-01-30
4,11897189,23,2025-01-30 10:21:57,460,12,0.0,0.0,0.0,NaN,NaN,4620,NaN,0,0,0,2025-01-30

In [4]:
df_agg = df.groupby('MerDateDay').apply(
    lambda x: pd.Series({
        'Total settings changed': ((x['MerType'] == 15)).sum(),
        'Total stops': ((x['MerType'] == 8) & (x['MerNumber'] == 0)).sum()
    })
)

df_agg.head(3)

/var/folders/pt/00xl4yzd64s0vbx9w9tzh94m0000gn/T/ipykernel_76430/2456108074.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_agg = df.groupby('MerDateDay').apply(

            Total settings changed  Total stops
MerDateDay
2025-01-30                     862          493
2025-01-31                    1366          312
2025-02-03                    1264          473

In [10]:
df['MerDate'] = pd.to_datetime(df['MerDate'])
df_agg_1h = df.set_index('MerDate').resample('1h').apply(
    lambda x: pd.Series({
        'Total settings changed': ((x['MerType'] == 15)).sum(),
        'Total stops scheduled': ((x['MerType'] == 8) & (x['MerNumber'] == 0)& (x['MerSubNumber'] == 1)).sum(),
        'Total stops conveyor full': ((x['MerType'] == 8) & (x['MerNumber'] == 0)& (x['MerSubNumber'] == 11)).sum(),
        'Total stops lane pressure': ((x['MerType'] == 8) & (x['MerNumber'] == 0)& (x['MerSubNumber'] == 2)).sum(),

        'Total stops': ((x['MerType'] == 8) & (x['MerNumber'] == 0)).sum()
    })
).reset_index()

df_agg_1h.head()

,MerDate,Total settings changed,Total stops scheduled,Total stops conveyor full,Total stops lane pressure,Total stops
0,2025-01-30 10:00:00,51,0,0,7,7
1,2025-01-30 11:00:00,60,2,0,20,26
2,2025-01-30 12:00:00,98,0,0,40,47
3,2025-01-30 13:00:00,84,1,0,32,41
4,2025-01-30 14:00:00,82,1,0,28,45